name: Status
run-name: Status
on:
  push:
  workflow_dispatch:

jobs:
  status:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the current branch
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Cache ./static/processed_images
        id: dir-processed-images
        uses: actions/cache@v5
        with:
          path: ./static/processed_images
          key: processed-images-${{ hashFiles('./static/img/**') }}
          restore-keys: |
            processed-images-

      - uses: taiki-e/install-action@v2
        with:
          tool: zola@0.21.0

      - name: Build the website
        run: zola build --minify
